# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/python:3.9.0-node
      - image: ethereum/client-go:v1.10.26
        command: "\
          --miner.gaslimit 12000000 \
          --http \
          --http.api personal,eth,net,web3,debug \
          --allow-insecure-unlock \
          --rpc.allow-unprotected-txs \
          --http.vhosts '*,localhost,host.docker.internal' \
          --http.corsdomain '*' \
          --http.addr '0.0.0.0' \
          --dev \
          --nodiscover --maxpeers 0 --mine \
          --miner.threads 1 \
          --verbosity 2 \
          --ignore-legacy-receipts"
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "curl pdm"
          command: "curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -"
      - run:
          name: "pdm install"
          command: "pdm install && git submodule update --init --recursive"
      - run:
          name: "clone bundler"
          command: git clone https://github.com/eth-infinitism/bundler.git
      - run:
          name: "yarn install for bundler"
          working_directory: "./bundler"
          command: yarn install && yarn preprocess
      - run:
          name: "deploy entry point"
          working_directory: "./bundler"
          command: yarn hardhat-deploy --network localhost
          background: true
      - run:
          name: "run bundler"
          working_directory: "./bundler"
          command: yarn bundler
          background: true
      - run:
          name: "pytest"
          command: "pdm run pytest --tb=no -rA -W ignore::DeprecationWarning --url http://localhost:3000/rpc  --ethereum-node http://127.0.0.1:8545/ --entry-point 0x2DF1592238420ecFe7f2431360e224707e77fA0E"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
